baseURL = "https://che-kwas.gitee.io"
languageCode = "zh-cn"
title = "Che's Notebook"
theme = "hugo-book"

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

[menu]
[[menu.after]]
  name = "Github"
  url = "https://github.com/che-kwas/che-kwas"
  weight = 10

[[menu.after]]
  name = "Leetcode"
  url = "https://leetcode-cn.com/u/chekwas/"
  weight = 20

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/che-kwas/che-kwas'
